/** Commander staples offered as one-tap adds in the deck builder.
 * Curated, not data-driven: these lists barely move year to year. */
export const STAPLE_CATEGORIES: { label: string; names: string[] }[] = [
  {
    label: 'Lands',
    names: [
      'Command Tower',
      'Exotic Orchard',
      'Evolving Wilds',
      'Terramorphic Expanse',
      'Reliquary Tower',
      "Rogue's Passage",
      'Myriad Landscape',
      'Path of Ancestry',
      'Ash Barrens',
      'Temple of the False God',
    ],
  },
  {
    label: 'Mana rocks',
    names: [
      'Sol Ring',
      'Arcane Signet',
      'Fellwar Stone',
      'Mind Stone',
      "Commander's Sphere",
      'Thought Vessel',
      'Worn Powerstone',
      'Hedron Archive',
      "Wayfarer's Bauble",
      'Thran Dynamo',
    ],
  },
  {
    label: 'Removal',
    names: [
      'Swords to Plowshares',
      'Path to Exile',
      'Beast Within',
      'Generous Gift',
      'Chaos Warp',
      'Anguished Unmaking',
      'Terminate',
      'Putrefy',
      'Rapid Hybridization',
      'Pongify',
    ],
  },
  {
    label: 'Board wipes',
    names: [
      'Blasphemous Act',
      'Wrath of God',
      'Damnation',
      'Toxic Deluge',
      'Cyclonic Rift',
      'Austere Command',
      'Farewell',
      'Vandalblast',
      'Evacuation',
      'Day of Judgment',
    ],
  },
  {
    label: 'Card draw',
    names: [
      'Rhystic Study',
      'Mystic Remora',
      'Phyrexian Arena',
      'Harmonize',
      "Night's Whisper",
      'Read the Bones',
      'Fact or Fiction',
      'Windfall',
      'Skullclamp',
      'Guardian Project',
    ],
  },
];
